version: 2

sources:
  - name: gz_raw_data
    schema: raw
    description: greenweez database for finance analysis
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: to LOWER column title
            tests:
              - not_null

      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: date_date
            description: aggregation by date for daily granularity
          - name: orders_id
            description: foreign key to ship
            tests:
              - not_null
              - unique

          - name: pdt_id
            description: foreign key to product
            tests:
              - not_null

          - name: revenue
            description: to calculate daily turnover, margin and operational margin
            tests:
              - not_null

          - name: quantity
            tests:
              - not_null

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key for the table
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: to calculate turnover
            tests:
              - not_null

          - name: shipping_fee_1
            description: double to clean

          - name: logCost
            description: to LOWER column title // to calculate operational margin
            tests:
              - not_null

          - name: ship_cost
            description: to calculate operational margin
            tests:
              - not_null
